name: flutter_assignment_oru_phone_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  provider: ^6.1.2
  fluttertoast: ^8.2.11
  flutter_launcher_icons: ^0.14.3
  pin_code_fields: ^8.0.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.5.2
  flutter_sticky_header: ^0.7.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  animate_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/oru_phone_logo_img.png"  # Path to your image
  adaptive_icon_foreground: "lib/assets/images/oru_phone_logo_img.png"  # Path to your image
  adaptive_icon_background: "#ffffff"
  adptive_icon_padding: true
  adaptive_icon_foreground_inset: 30

flutter:
  uses-material-design: true
  fonts: 
    - family: Poppins
      fonts: 
        - asset: lib/assets/fonts/poppins_regular.ttf
  assets: 
    - lib/assets/svgs/
    - lib/assets/images/
