name: flutter_assignment_oru_phone_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts: 
    - family: Poppins
      fonts: 
        - asset: lib/assets/fonts/poppins_regular.ttf
  assets: 
    - lib/assets/svgs/
    - lib/assets/images/
